package main

import (
	"fmt"
	"log"
	"path"
	"reflect"
	"text/template"

	"github.com/Masterminds/sprig"
	"github.com/eddycharly/terraform-provider-kops/pkg/api/config"
	"github.com/eddycharly/terraform-provider-kops/pkg/api/datasources"
	"github.com/eddycharly/terraform-provider-kops/pkg/api/kube"
	"github.com/eddycharly/terraform-provider-kops/pkg/api/resources"
	"github.com/eddycharly/terraform-provider-kops/pkg/api/utils"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kops/pkg/apis/kops"
)

var mappings = map[string]string{
	"github.com/eddycharly/terraform-provider-kops/pkg/api/config":      "config",
	"github.com/eddycharly/terraform-provider-kops/pkg/api/datasources": "datasources",
	"github.com/eddycharly/terraform-provider-kops/pkg/api/kube":        "kube",
	"github.com/eddycharly/terraform-provider-kops/pkg/api/resources":   "resources",
	"github.com/eddycharly/terraform-provider-kops/pkg/api/utils":       "utils",
	"k8s.io/kops/pkg/apis/kops":                                         "kops",
	"k8s.io/api/core/v1":                                                "core",
	"k8s.io/apimachinery/pkg/apis/meta/v1":                              "meta",
}

func buildDoc(t reflect.Type, p string, funcMaps ...template.FuncMap) {
	fileName := toSnakeCase(fieldName(t.Name())) + ".md"
	executeTemplate(t, docsTemplate, p, fileName, funcMaps...)
}

func buildSchema(t reflect.Type, p, scope string, funcMaps ...template.FuncMap) {
	fileName := fmt.Sprintf("%s_%s.generated.go", scope, t.Name())
	executeTemplate(t, schemasTemplate, p, fileName, funcMaps...)
}

func buildTests(t reflect.Type, p, scope string, funcMaps ...template.FuncMap) {
	fileName := fmt.Sprintf("%s_%s.generated_test.go", scope, t.Name())
	executeTemplate(t, testsTemplate, p, fileName, funcMaps...)
}

type generated struct {
	t reflect.Type
	o *options
}

func generate(i interface{}, opts ...func(o *options)) generated {
	t := reflect.TypeOf(i)
	o := newOptions()
	for _, opt := range opts {
		opt(o)
	}
	if err := o.verify(t); err != nil {
		panic(err)
	}
	return generated{
		t: t,
		o: o,
	}
}

func build(scope, docs string, parser *parser, g ...generated) {
	o := map[reflect.Type]*options{}
	for _, gen := range g {
		o[gen.t] = gen.o
	}
	for _, gen := range g {
		funcMaps := []template.FuncMap{
			reflectFuncs(gen.t, mappings, parser),
			optionFuncs(scope == "DataSource", o, parser),
			schemaFuncs(scope),
			sprig.TxtFuncMap(),
		}
		buildSchema(gen.t, path.Join("pkg/schemas", mappings[gen.t.PkgPath()]), scope, funcMaps...)
		buildTests(gen.t, path.Join("pkg/schemas", mappings[gen.t.PkgPath()]), scope, funcMaps...)
		if gen.o.doc != nil {
			buildDoc(gen.t, docs, append(funcMaps, docFuncs(gen.o.doc.header, gen.o.doc.footer, parser, o))...)
		}
	}
}

func main() {
	log.Println("loading packages...")
	parser, err := initParser(
		"github.com/eddycharly/terraform-provider-kops/pkg/api/config",
		"github.com/eddycharly/terraform-provider-kops/pkg/api/datasources",
		"github.com/eddycharly/terraform-provider-kops/pkg/api/kube",
		"github.com/eddycharly/terraform-provider-kops/pkg/api/resources",
	)
	if err != nil {
		panic(err)
	}
	log.Println("generating schemas, expanders and flatteners...")
	build(
		"Resource",
		"docs/resources/",
		parser,
		generate(resources.Cluster{},
			version(4),
			required("Name"),
			computedOnly("Revision"),
			sensitive("AdminSshKey"),
			forceNew("Name"),
			doc(resourceClusterHeader, resourceClusterFooter),
		),
		generate(resources.InstanceGroup{},
			version(2),
			required("ClusterName", "Name"),
			forceNew("ClusterName", "Name"),
			computedOnly("Revision"),
			doc(resourceInstanceGroupHeader, resourceInstanceGroupFooter),
		),
		generate(resources.ClusterUpdater{},
			required("ClusterName"),
			computedOnly("Revision", "ProviderVersion"),
			doc(resourceClusterUpdaterHeader, ""),
		),
		generate(utils.RollingUpdateOptions{},
			noSchema(),
		),
		generate(resources.ClusterSecrets{},
			sensitive("DockerConfig", "ClusterCaCert", "ClusterCaKey"),
			computed("ClusterCaCert", "ClusterCaKey"),
		),
		generate(resources.ValidateOptions{}),
		generate(utils.ValidateOptions{},
			noSchema(),
		),
		generate(resources.ApplyOptions{}),
		generate(kops.ClusterSpec{},
			noSchema(),
			exclude("GossipConfig", "DNSControllerGossipConfig", "Target"),
			rename("EtcdClusters", "EtcdCluster"),
			required("CloudProvider", "EtcdClusters", "Networking"),
			computed("ConfigBase", "IAM"),
		),
		generate(kops.InstanceMetadataOptions{}),
		generate(kops.NodeTerminationHandlerSpec{},
			required("Enabled", "EnableSpotInterruptionDraining"),
		),
		generate(kops.MetricsServerConfig{},
			required("Insecure"),
		),
		generate(kops.ClusterAutoscalerConfig{},
			required("SkipNodesWithSystemPods", "SkipNodesWithLocalStorage"),
		),
		generate(kops.AddonSpec{},
			required("Manifest"),
		),
		generate(kops.EgressProxySpec{},
			required("HTTPProxy"),
		),
		generate(kops.HTTPProxy{},
			required("Host", "Port"),
		),
		generate(kops.ContainerdConfig{}),
		generate(kops.PackagesConfig{}),
		generate(kops.DockerConfig{}),
		generate(kops.KubeDNSConfig{}),
		generate(kops.KubeAPIServerConfig{},
			nullable("AnonymousAuth"),
		),
		generate(kops.KubeControllerManagerConfig{}),
		generate(kops.CloudControllerManagerConfig{}),
		generate(kops.KubeSchedulerConfig{}),
		generate(kops.KubeProxyConfig{},
			required("Enabled"),
		),
		generate(kops.KubeletConfigSpec{},
			nullable("AnonymousAuth", "CPUCFSQuota"),
		),
		generate(kops.CloudConfiguration{}),
		generate(kops.ExternalDNSConfig{}),
		generate(kops.OpenstackLoadbalancerConfig{}),
		generate(kops.OpenstackMonitor{}),
		generate(kops.OpenstackRouter{}),
		generate(kops.OpenstackBlockStorageConfig{}),
		generate(kops.LeaderElectionConfiguration{}),
		generate(kops.NodeLocalDNSConfig{}),
		generate(kops.AuthenticationSpec{}),
		generate(kops.AuthorizationSpec{}),
		generate(kops.NodeAuthorizationSpec{}),
		generate(kops.Assets{}),
		generate(kops.IAMSpec{}),
		generate(kops.KopeioAuthenticationSpec{}),
		generate(kops.AWSAuthenticationSpec{}),
		generate(kops.AlwaysAllowAuthorizationSpec{}),
		generate(kops.RBACAuthorizationSpec{}),
		generate(kops.NodeAuthorizerSpec{}),
		generate(kops.InstanceGroupSpec{},
			noSchema(),
			required("Role", "MinSize", "MaxSize", "MachineType", "Subnets"),
			computed("Image", "Manager", "Kubelet"),
		),
		generate(kops.AccessLogSpec{}),
		generate(kops.DNSAccessSpec{}),
		generate(kops.LoadBalancerAccessSpec{},
			required("Type"),
		),
		generate(kops.EtcdClusterSpec{},
			required("Name", "Members"),
			rename("Members", "Member"),
		),
		generate(kops.EtcdBackupSpec{},
			required("BackupStore", "Image"),
		),
		generate(kops.EtcdManagerSpec{}),
		generate(kops.EtcdMemberSpec{},
			required("Name", "InstanceGroup"),
		),
		generate(kops.EnvVar{},
			required("Name"),
		),
		generate(kops.ClusterSubnetSpec{},
			required("Name", "Type"),
			computed("CIDR"),
		),
		generate(kops.TopologySpec{},
			required("ControlPlane", "Nodes", "DNS"),
		),
		generate(kops.BastionSpec{},
			required("PublicName"),
			rename("PublicName", "BastionPublicName"),
		),
		generate(kops.BastionLoadBalancerSpec{},
			required("Type"),
		),
		generate(kops.DNSAccessSpec{}),
		generate(kops.NetworkingSpec{},
			rename("Subnets", "Subnet"),
			required("Subnets", "NetworkID", "Topology"),
			computed("NetworkCIDR", "NonMasqueradeCIDR"),
			nullable("TagSubnets"),
		),
		generate(kops.ClassicNetworkingSpec{}),
		generate(kops.KubenetNetworkingSpec{}),
		generate(kops.ExternalNetworkingSpec{}),
		generate(kops.CNINetworkingSpec{}),
		generate(kops.KopeioNetworkingSpec{}),
		generate(kops.WeaveNetworkingSpec{}),
		generate(kops.FlannelNetworkingSpec{}),
		generate(kops.CalicoNetworkingSpec{}),
		generate(kops.CanalNetworkingSpec{}),
		generate(kops.KuberouterNetworkingSpec{}),
		generate(kops.RomanaNetworkingSpec{}),
		generate(kops.AmazonVPCNetworkingSpec{}),
		generate(kops.CiliumNetworkingSpec{},
			required("PreallocateBPFMaps", "EnableRemoteNodeIdentity"),
		),
		generate(kops.HubbleSpec{}),
		generate(kops.LyftVPCNetworkingSpec{}),
		generate(kops.GCENetworkingSpec{}),
		generate(kops.VolumeSpec{},
			required("Device"),
		),
		generate(kops.VolumeMountSpec{},
			required("Device", "Filesystem", "Path"),
		),
		generate(kops.MixedInstancesPolicySpec{},
			nullable("OnDemandBase", "OnDemandAboveBase"),
		),
		generate(kops.UserData{},
			required("Name", "Type", "Content"),
		),
		generate(kops.IAMProfileSpec{},
			required("Profile"),
		),
		generate(kops.HookSpec{},
			required("Name"),
		),
		generate(kops.ExecContainerAction{},
			required("Image"),
		),
		generate(kops.FileAssetSpec{},
			required("Name", "Path", "Content"),
		),
		generate(kops.RollingUpdate{}),
		// 1.20
		generate(resources.RollingUpdateOptions{}),
		generate(kops.EBSCSIDriverSpec{}),
		generate(kops.NTPConfig{}),
		generate(kops.CertManagerConfig{},
			required("Enabled", "Managed"),
		),
		generate(kops.LoadBalancerControllerSpec{}),
		generate(kops.GossipConfigSecondary{}),
		generate(kops.LoadBalancerSubnetSpec{}),
		generate(kops.DNSControllerGossipConfigSecondary{}),
		generate(kops.OpenstackNetwork{}),
		// 1.21
		generate(kops.WarmPoolSpec{}),
		generate(kops.ServiceAccountIssuerDiscoveryConfig{}),
		generate(kops.SnapshotControllerConfig{}),
		generate(kops.ServiceAccountExternalPermission{}),
		generate(kops.AWSPermission{}),
		// 1.22
		generate(kops.NodeProblemDetectorConfig{}),
		generate(kops.NvidiaGPUConfig{}),
		generate(kops.AccessLogSpec{}),
		generate(kops.OpenstackMetadata{}),
		generate(corev1.Toleration{}),
		generate(corev1.Affinity{}),
		generate(corev1.NodeAffinity{}),
		generate(corev1.PodAffinity{}),
		generate(corev1.PodAntiAffinity{}),
		generate(corev1.PodAffinityTerm{}),
		generate(corev1.WeightedPodAffinityTerm{}),
		generate(corev1.PreferredSchedulingTerm{}),
		generate(corev1.NodeSelector{}),
		generate(corev1.NodeSelectorTerm{}),
		generate(corev1.NodeSelectorRequirement{}),
		generate(metav1.LabelSelector{}),
		generate(metav1.LabelSelectorRequirement{}),
		// 1.23
		generate(kops.PDCSIDriver{}),
		generate(kops.AWSAuthenticationIdentityMappingSpec{}),
		generate(kops.PodIdentityWebhookSpec{}),
		//	1.24
		generate(kops.CloudProviderSpec{}),
		generate(kops.KarpenterConfig{}),
		generate(kops.RouteSpec{}),
		generate(kops.AcceleratorConfig{}),
		generate(kops.AWSSpec{}),
		generate(kops.AzureSpec{}),
		generate(kops.DOSpec{}),
		generate(kops.GCESpec{}),
		generate(kops.HetznerSpec{}),
		generate(kops.OpenstackSpec{}),
		generate(kops.InstanceRequirementsSpec{}),
		generate(kops.MinMaxSpec{}),
		generate(kops.Runc{}),
		// 1.26
		generate(kops.ScalewaySpec{}),
		generate(kops.APISpec{}),
		generate(kops.DCGMExporterConfig{}),
		generate(kops.LoadBalancerSpec{}),
	)
	build(
		"Config",
		"docs/guides/",
		parser,
		generate(config.Provider{},
			required("StateStore"),
			doc(configProviderHeader, ""),
		),
		generate(config.Aws{}),
		generate(config.AwsAssumeRole{}),
		generate(config.Openstack{}),
		generate(config.Klog{},
			nullable("Verbosity"),
		),
	)
	build(
		"DataSource",
		"docs/data-sources/",
		parser,
		generate(datasources.KubeConfig{},
			required("ClusterName"),
			computed("Admin", "Internal"),
			doc(dataKubeConfigHeader, ""),
		),
		generate(datasources.ClusterStatus{},
			required("ClusterName"),
			doc(dataClusterStatusHeader, ""),
		),
		generate(resources.Cluster{},
			version(4),
			required("Name"),
			exclude("Revision"),
			doc(dataClusterHeader, ""),
		),
		generate(resources.InstanceGroup{},
			version(2),
			required("ClusterName", "Name"),
			exclude("Revision"),
			doc(dataInstanceGroupHeader, ""),
		),
		generate(resources.ClusterSecrets{},
			sensitive("DockerConfig", "ClusterCaCert", "ClusterCaKey"),
		),
		generate(kube.Config{},
			noSchema(),
			sensitive("KubeUser", "KubePassword", "CaCerts", "ClientCert", "ClientKey"),
		),
		generate(kops.ClusterSpec{},
			exclude("GossipConfig", "DNSControllerGossipConfig", "Target"),
			rename("EtcdClusters", "EtcdCluster"),
		),
		generate(kops.InstanceMetadataOptions{}),
		generate(kops.NodeTerminationHandlerSpec{}),
		generate(kops.MetricsServerConfig{}),
		generate(kops.ClusterAutoscalerConfig{}),
		generate(kops.AddonSpec{}),
		generate(kops.GossipConfig{}),
		generate(kops.ClusterSubnetSpec{}),
		generate(kops.TopologySpec{}),
		generate(kops.DNSControllerGossipConfig{}),
		generate(kops.EgressProxySpec{}),
		generate(kops.EtcdClusterSpec{},
			rename("Members", "Member"),
		),
		generate(kops.ContainerdConfig{}),
		generate(kops.PackagesConfig{}),
		generate(kops.DockerConfig{}),
		generate(kops.KubeDNSConfig{}),
		generate(kops.KubeAPIServerConfig{},
			nullable("AnonymousAuth"),
		),
		generate(kops.KubeControllerManagerConfig{}),
		generate(kops.CloudControllerManagerConfig{}),
		generate(kops.KubeSchedulerConfig{}),
		generate(kops.KubeProxyConfig{}),
		generate(kops.CloudConfiguration{}),
		generate(kops.ExternalDNSConfig{}),
		generate(kops.NetworkingSpec{},
			rename("Subnets", "Subnet"),
			nullable("TagSubnets"),
		),
		generate(kops.AccessLogSpec{}),
		generate(kops.AuthenticationSpec{}),
		generate(kops.DNSAccessSpec{}),
		generate(kops.LoadBalancerAccessSpec{}),
		generate(kops.KopeioAuthenticationSpec{}),
		generate(kops.AWSAuthenticationSpec{}),
		generate(kops.LeaderElectionConfiguration{}),
		generate(kops.AuthorizationSpec{}),
		generate(kops.NodeAuthorizationSpec{}),
		generate(kops.Assets{}),
		generate(kops.IAMSpec{}),
		generate(kops.AlwaysAllowAuthorizationSpec{}),
		generate(kops.RBACAuthorizationSpec{}),
		generate(kops.HTTPProxy{}),
		generate(kops.EtcdMemberSpec{}),
		generate(kops.EtcdBackupSpec{}),
		generate(kops.EtcdManagerSpec{}),
		generate(kops.NodeLocalDNSConfig{}),
		generate(kops.ClassicNetworkingSpec{}),
		generate(kops.KubenetNetworkingSpec{}),
		generate(kops.ExternalNetworkingSpec{}),
		generate(kops.CNINetworkingSpec{}),
		generate(kops.EnvVar{}),
		generate(kops.KopeioNetworkingSpec{}),
		generate(kops.WeaveNetworkingSpec{}),
		generate(kops.FlannelNetworkingSpec{}),
		generate(kops.CalicoNetworkingSpec{}),
		generate(kops.CanalNetworkingSpec{}),
		generate(kops.KuberouterNetworkingSpec{}),
		generate(kops.RomanaNetworkingSpec{}),
		generate(kops.AmazonVPCNetworkingSpec{}),
		generate(kops.CiliumNetworkingSpec{}),
		generate(kops.HubbleSpec{}),
		generate(kops.LyftVPCNetworkingSpec{}),
		generate(kops.GCENetworkingSpec{}),
		generate(kops.NodeAuthorizerSpec{}),
		generate(kops.OpenstackLoadbalancerConfig{}),
		generate(kops.OpenstackMonitor{}),
		generate(kops.OpenstackRouter{}),
		generate(kops.OpenstackBlockStorageConfig{}),
		generate(kops.BastionSpec{},
			rename("PublicName", "BastionPublicName"),
		),
		generate(kops.DNSAccessSpec{}),
		generate(kops.BastionLoadBalancerSpec{}),
		generate(kops.InstanceGroupSpec{},
			noSchema(),
		),
		generate(kops.VolumeSpec{}),
		generate(kops.VolumeMountSpec{}),
		generate(kops.HookSpec{}),
		generate(kops.FileAssetSpec{}),
		generate(kops.KubeletConfigSpec{},
			nullable("AnonymousAuth", "CPUCFSQuota"),
		),
		generate(kops.MixedInstancesPolicySpec{},
			nullable("OnDemandBase", "OnDemandAboveBase"),
		),
		generate(kops.UserData{}),
		generate(kops.LoadBalancerAccessSpec{}),
		generate(kops.IAMProfileSpec{}),
		generate(kops.RollingUpdate{}),
		generate(kops.ExecContainerAction{}),
		// 1.20
		generate(kops.EBSCSIDriverSpec{}),
		generate(kops.NTPConfig{}),
		generate(kops.CertManagerConfig{}),
		generate(kops.LoadBalancerControllerSpec{}),
		generate(kops.GossipConfigSecondary{}),
		generate(kops.LoadBalancerSubnetSpec{}),
		generate(kops.DNSControllerGossipConfigSecondary{}),
		generate(kops.OpenstackNetwork{}),
		// 1.21
		generate(kops.WarmPoolSpec{}),
		generate(kops.ServiceAccountIssuerDiscoveryConfig{}),
		generate(kops.SnapshotControllerConfig{}),
		generate(kops.ServiceAccountExternalPermission{}),
		generate(kops.AWSPermission{}),
		// 1.22
		generate(kops.NodeProblemDetectorConfig{}),
		generate(kops.NvidiaGPUConfig{}),
		generate(kops.AccessLogSpec{}),
		generate(kops.OpenstackMetadata{}),
		generate(corev1.Toleration{}),
		generate(corev1.Affinity{}),
		generate(corev1.NodeAffinity{}),
		generate(corev1.PodAffinity{}),
		generate(corev1.PodAntiAffinity{}),
		generate(corev1.PodAffinityTerm{}),
		generate(corev1.WeightedPodAffinityTerm{}),
		generate(corev1.PreferredSchedulingTerm{}),
		generate(corev1.NodeSelector{}),
		generate(corev1.NodeSelectorTerm{}),
		generate(corev1.NodeSelectorRequirement{}),
		generate(metav1.LabelSelector{}),
		generate(metav1.LabelSelectorRequirement{}),
		// 1.23
		generate(kops.PDCSIDriver{}),
		generate(kops.AWSAuthenticationIdentityMappingSpec{}),
		generate(kops.PodIdentityWebhookSpec{}),
		//	1.24
		generate(kops.CloudProviderSpec{}),
		generate(kops.KarpenterConfig{}),
		generate(kops.RouteSpec{}),
		generate(kops.AcceleratorConfig{}),
		generate(kops.AWSSpec{}),
		generate(kops.AzureSpec{}),
		generate(kops.DOSpec{}),
		generate(kops.GCESpec{}),
		generate(kops.HetznerSpec{}),
		generate(kops.OpenstackSpec{}),
		generate(kops.InstanceRequirementsSpec{}),
		generate(kops.MinMaxSpec{}),
		generate(kops.Runc{}),
		// 1.26
		generate(kops.ScalewaySpec{}),
		generate(kops.APISpec{}),
		generate(kops.DCGMExporterConfig{}),
		generate(kops.LoadBalancerSpec{}),
	)
}
